import { InterviewItem } from "../types/sap";

export const INTERVIEW_BANK: InterviewItem[] = [
  {
    "id": "int-01",
    "module": "MM",
    "category": "Procurement",
    "tier": "Basic",
    "question": "What is the difference between a Purchase Requisition and a Purchase Order in SAP S/4HANA?",
    "idealAnswer": "A Purchase Requisition (PR) is an internal planning and request document created by user departments or automatically generated by MRP Live (MD01N) to communicate material requirements. It has no legal standing with suppliers. A Purchase Order (PO) is a formal, legally binding commercial contract sent to an external supplier specifying exact quantities, unit prices, delivery dates, Incoterms, and payment terms.",
    "keyPhrasesExpected": [
      "Internal request vs External legal contract",
      "MRP generation (MD01N)",
      "Vendor commercial commitment",
      "Document types NB vs PR"
    ],
    "consultantThinkingTip": "Emphasize that PRs drive internal organizational governance and budget availability, while POs establish external legal liability and authorize warehouse goods receipt.",
    "followUpQuestions": [
      "Can a PO be created without a reference to a PR?",
      "What is transaction ME59N used for in automated purchasing?"
    ],
    "difficultyScore": 2
  },
  {
    "id": "int-02",
    "module": "MM",
    "category": "Master Data",
    "tier": "Basic",
    "question": "What is the SAP S/4HANA Business Partner (BP) concept and how does Customer Vendor Integration (CVI) work?",
    "idealAnswer": "In SAP S/4HANA, the Business Partner (T-Code: BP) is the mandatory single point of entry for managing master data for customers, vendors, and contacts. Classic ECC transactions (XK01, MK01, FK01) are obsolete and redirect to BP. Customer Vendor Integration (CVI) synchronization runs automatically in the background: when a Business Partner is created with role FLVN00 (FI Vendor) or FLVN01 (Purchasing Supplier), CVI updates underlying tables LFA1, LFB1, and LFM1 while linking to the master BUT000 record.",
    "keyPhrasesExpected": [
      "Single point of entry",
      "CVI background synchronization",
      "BP Roles FLVN00 and FLVN01",
      "Tables BUT000 and LFA1",
      "Obsolete XK01/MK01"
    ],
    "consultantThinkingTip": "Explain how 'Same Number' configuration between BP grouping and Vendor account group simplifies master data governance for business users.",
    "followUpQuestions": [
      "What table maps BP GUID to Supplier Number (IBPBDL)?",
      "How do you resolve CVI pre-check errors during Brownfield conversion?"
    ],
    "difficultyScore": 3
  },
  {
    "id": "int-03",
    "module": "MM",
    "category": "Enterprise Structure",
    "tier": "Basic",
    "question": "Describe the SAP MM Enterprise Structure hierarchy and explain the relationship between Company Code, Plant, and Storage Location.",
    "idealAnswer": "The MM enterprise structure consists of: 1) Client (highest administrative unit), 2) Company Code (independent legal accounting entity with balance sheet and P&L), 3) Plant (physical manufacturing, warehouse, or operational facility assigned to exactly one Company Code in OX18), 4) Storage Location (physical bin/warehouse sub-division within a plant in OX09), 5) Purchasing Organization (commercial buying entity responsible for negotiating contracts; can be cross-company, company-specific, or plant-specific).",
    "keyPhrasesExpected": [
      "Client -> Company Code -> Plant -> Storage Location",
      "OX18 Assignment",
      "Purchasing Organization flexibility (OX01 / OX17)",
      "Valuation Area at Plant level (OX14)"
    ],
    "consultantThinkingTip": "Always mention that in modern S/4HANA, the Valuation Area is mandatory at the Plant level to support material valuation and product costing.",
    "followUpQuestions": [
      "Can one plant be assigned to two company codes?",
      "What is a Reference Purchasing Organization?"
    ],
    "difficultyScore": 3
  },
  {
    "id": "int-04",
    "module": "MM",
    "category": "Inventory Management",
    "tier": "Basic",
    "question": "What is the difference between Stock Overview (MMBE) and Warehouse Stock (MB52)?",
    "idealAnswer": "MMBE (Stock Overview) provides a deep single-material hierarchy view displaying stock distribution across Company Code, Plant, Storage Location, Batch, and Stock Types (Unrestricted, Quality Inspection, Blocked, On-Order, In-Transit). MB52 (Warehouse Stock) is a multi-material list report designed for mass reporting of quantities and total financial inventory valuation across one or more plants and storage locations.",
    "keyPhrasesExpected": [
      "MMBE is single-material hierarchy",
      "MB52 is multi-material with financial valuation",
      "Stock Types breakdown",
      "Real-time read from MATDOC"
    ],
    "consultantThinkingTip": "Note that both transactions in S/4HANA read real-time aggregated data directly from the universal table MATDOC via Core Data Services (CDS).",
    "followUpQuestions": [
      "What transaction displays inventory movement history (MB51)?",
      "What is the difference between unrestricted and quality inspection stock?"
    ],
    "difficultyScore": 2
  },
  {
    "id": "int-05",
    "module": "MM",
    "category": "Inventory Management",
    "tier": "Intermediate",
    "question": "Explain the complete accounting flow of Movement Type 101 Goods Receipt and subsequent MIRO Invoice Verification with a price variance.",
    "idealAnswer": "At MIGO 101 Goods Receipt (Standard Price Control 'S'): System debits Raw Material Inventory (BSX) at standard price ($10) and credits GR/IR Clearing (WRX) at PO price ($12). The $2 variance debits Purchase Price Difference (PRD). At MIRO Invoice Receipt: System debits GR/IR Clearing (WRX) for $12 (clearing the liability) and credits Vendor Accounts Payable (KBS/BSEG) for the invoice total ($13 if supplier billed extra $1). The extra $1 variance debits Price Difference (PRD).",
    "keyPhrasesExpected": [
      "Debit BSX at Standard Price",
      "Credit WRX at PO Price",
      "PRD Price Difference variance",
      "Debit WRX and Credit Vendor in MIRO",
      "3-Way Match"
    ],
    "consultantThinkingTip": "Always state whether Price Control is Standard (S) or Moving Average (V) because Moving Average price absorbs the variance into material inventory value if stock coverage exists.",
    "followUpQuestions": [
      "What happens if Price Control is Moving Average V and current stock is less than invoiced quantity?",
      "How does MR11 clear orphaned GR/IR line items?"
    ],
    "difficultyScore": 5
  },
  {
    "id": "int-06",
    "module": "MM",
    "category": "Procurement",
    "tier": "Intermediate",
    "question": "What is the difference between a Quantity Contract (MK), a Value Contract (WK), and a Scheduling Agreement (LP/LPA)?",
    "idealAnswer": "A Quantity Contract (MK) is an agreement where total target quantity is committed (e.g. 10,000 units). A Value Contract (WK) is an agreement where total monetary value is committed (e.g. $1,000,000). Neither contract type contains delivery dates; both require operational Purchase Orders (Release Orders) in ME21N to request delivery and cannot receive direct MIGO goods receipts. A Scheduling Agreement (LP/LPA) is a long-term agreement that includes rolling delivery dates (Schedule Lines in table EKET) generated directly by MRP, and goods receipts (MIGO) are posted directly against the scheduling agreement without creating separate POs.",
    "keyPhrasesExpected": [
      "Contracts require Release Orders (POs)",
      "Scheduling Agreements contain Schedule Lines (EKET)",
      "Direct MIGO against SA vs indirect PO release for Contracts",
      "JIT / Forecast releases in LPA"
    ],
    "consultantThinkingTip": "Highlight that automotive and repetitive discrete manufacturing heavily rely on Scheduling Agreements (LPA) with EDI 830/862 integration to minimize purchasing paperwork.",
    "followUpQuestions": [
      "What transaction is used to maintain delivery schedule lines manually (ME38)?",
      "How does MRP Live automatically populate scheduling lines?"
    ],
    "difficultyScore": 6
  },
  {
    "id": "int-07",
    "module": "MM",
    "category": "Special Procurement",
    "tier": "Intermediate",
    "question": "Walk through the complete Subcontracting procurement process in SAP MM, including movement types, document flow, and accounting entries.",
    "idealAnswer": "1) Purchase Order created with Item Category 'L' (Subcontracting) referencing BOM components. 2) Movement Type 541 transfers raw components from plant stock to Subcontractor Special Stock 'O' (non-valuated transfer). 3) Subcontractor processes components and delivers finished good. 4) Goods Receipt (MIGO 101) receives finished good and simultaneously triggers Movement Type 543 to auto-consume components from special stock 'O'. 5) Accounting: Debit Finished Inventory (BSX), Credit Subcontracting Change in Stock (BSV), Debit Subcontracting Service Labor (FRL), Credit GR/IR (WRX), Debit Raw Material Consumption (VBO), Credit Raw Material Inventory (BSX).",
    "keyPhrasesExpected": [
      "Item Category L",
      "Movement 541 to Special Stock O",
      "Movement 101 finished good + Movement 543 auto-consumption",
      "OBYC keys: BSX, BSV, FRL, WRX, VBO"
    ],
    "consultantThinkingTip": "Emphasize that the client retains title and inventory balance sheet ownership of the raw materials throughout the subcontracting cycle.",
    "followUpQuestions": [
      "How do you handle by-products returned by the subcontractor (Movement 545)?",
      "What is transaction ME2O used for?"
    ],
    "difficultyScore": 7
  },
  {
    "id": "int-08",
    "module": "MM",
    "category": "Special Procurement",
    "tier": "Intermediate",
    "question": "How does Vendor Consignment procurement work in SAP MM and how is settlement executed?",
    "idealAnswer": "In Vendor Consignment, the supplier stores goods at the buyer's warehouse, but ownership remains with the vendor until withdrawal. 1) PO created with Item Category 'K' (no price entered; price is pulled from Consignment Info Record). 2) Goods Receipt (MIGO 101 K) receives vendor consignment stock into the warehouse without financial postings. 3) When consumed, Transfer Posting (Movement 411 K) moves stock to own unrestricted inventory (or Movement 201 K consumes directly to Cost Center). S/4HANA posts Debit Inventory (BSX) / Credit Consignment Payables (KON). 4) Settlement is executed periodically via transaction MRKO without entering manual invoices in MIRO.",
    "keyPhrasesExpected": [
      "Item Category K",
      "Non-valuated 101 K Goods Receipt",
      "Transfer Posting 411 K triggers liability",
      "OBYC Transaction Key KON",
      "MRKO Automated Settlement"
    ],
    "consultantThinkingTip": "Stress that Consignment reduces working capital by keeping inventory off the balance sheet until the exact second it is physically consumed in production.",
    "followUpQuestions": [
      "Can you change the price on a Consignment Purchase Order?",
      "What happens if Consignment Info Record price expires before 411 K withdrawal?"
    ],
    "difficultyScore": 6
  },
  {
    "id": "int-09",
    "module": "MM",
    "category": "Configuration",
    "tier": "Advanced",
    "question": "Can you explain the 5 building blocks of Condition Technique in SAP MM Pricing and how Schema Determination works?",
    "idealAnswer": "Condition Technique consists of: 1) Condition Tables (stores search key combinations, e.g. Table 017 Vendor/Material/Plant), 2) Access Sequences (search strategy checking tables from most specific to general), 3) Condition Types (pricing elements like PB00 gross price, RA01 % discount, FRA1 freight), 4) Calculation Schema (formula table defining calculation steps, base lines, accrual keys, and subtotals in M/08), 5) Schema Determination (assigns calculation schema in OMFO based on Schema Group Purchasing Org in T024E and Schema Group Vendor in LFM1).",
    "keyPhrasesExpected": [
      "Condition Tables (A-tables)",
      "Access Sequence (M/07)",
      "Condition Types (M/06)",
      "Calculation Schema (M/08)",
      "Schema Determination (OMFO)",
      "Schema Group Purchasing Org + Schema Group Vendor"
    ],
    "consultantThinkingTip": "Explain how Planned Delivery Costs (Freight FRA1) require the 'Accruals' checkbox and an Accrual Account Key (FR1) in the schema to post liability to a freight carrier.",
    "followUpQuestions": [
      "What is the difference between PB00 and PBXX?",
      "Where are condition values stored in S/4HANA (PRCD_ELEMENTS)?"
    ],
    "difficultyScore": 8
  },
  {
    "id": "int-10",
    "module": "MM",
    "category": "Configuration",
    "tier": "Advanced",
    "question": "Explain how S/4HANA Flexible Workflow for Purchase Orders is configured and how it replaces classic CEKKO release strategies.",
    "idealAnswer": "Classic Release Strategy relied on Classification (Class Type 032), Characteristics in CT04 referencing communication structure CEKKO, and release codes approved via GUI transaction ME29N. S/4HANA Flexible Workflow (Scenario WS00800238) is configured via Fiori App 'Manage Workflows for Purchase Orders'. It evaluates dynamic preconditions (Amount, Plant, Purchasing Group), supports parallel/sequential multi-step approvals, determines recipients dynamically (Manager of Requester, Cost Center Owner, BAdI MMPUR_WORKFLOW_AGENTS_V2), and routes approval tasks directly to smartphones via Fiori 'My Inbox' (F0862).",
    "keyPhrasesExpected": [
      "Fiori App 'Manage Workflows for Purchase Orders'",
      "Scenario WS00800238",
      "My Inbox (F0862) mobile approvals",
      "Preconditions and dynamic recipient determination",
      "BAdI MMPUR_WORKFLOW_AGENTS_V2",
      "Replaces CEKKO/CEBAN classification"
    ],
    "consultantThinkingTip": "Emphasize that Flexible Workflow is Clean Core compliant and eliminates complex ABAP workflow templates (SWDD).",
    "followUpQuestions": [
      "What happens if both CEKKO and Flexible Workflow are configured for the same PO document type?",
      "How do you configure push notifications for SAP Mobile Start?"
    ],
    "difficultyScore": 8
  },
  {
    "id": "int-11",
    "module": "MM",
    "category": "Configuration",
    "tier": "Advanced",
    "question": "What is the 7-step account determination search chain in SAP MM-FI Automatic Account Determination (OBYC)?",
    "idealAnswer": "1) Chart of Accounts (determined from Company Code). 2) Valuation Grouping Code / Valuation Modifier (groups plants in OMWD/T001K). 3) Valuation Class (assigned to material in MBEW-BKLAS via Material Type in OMS2). 4) Transaction Key (internal posting trigger: BSX Inventory, WRX GR/IR, PRD Price Difference, GBB Consumption). 5) Account Modifier / General Modification (sub-divides GBB based on movement purpose: VBR Cost Center, VNG Scrap, BSA Initial Stock 561, INV Physical Inventory). 6) Table T030 lookup: Chart of Accounts + Transaction Key + Valuation Modifier + Account Modifier + Valuation Class -> G/L Account. 7) Posting Keys (89/99 for stock, 40/50 for G/L).",
    "keyPhrasesExpected": [
      "Chart of Accounts -> Valuation Grouping (OMWD) -> Valuation Class (MBEW) -> Transaction Key -> Account Modifier -> Table T030 G/L Account",
      "OBYC Keys: BSX, WRX, PRD, GBB",
      "Account Modifiers: VBR, VNG, BSA, INV"
    ],
    "consultantThinkingTip": "Be ready to write out the exact debit/credit entries for standard scenarios on a whiteboard.",
    "followUpQuestions": [
      "What transaction activates valuation grouping code (OMWM)?",
      "Why should inventory G/L accounts have 'Post Automatically Only' flagged in FS00?"
    ],
    "difficultyScore": 8
  },
  {
    "id": "int-12",
    "module": "MM",
    "category": "Troubleshooting",
    "tier": "Troubleshooting",
    "question": "A buyer attempts to post MIGO Goods Receipt, but the system terminates with error 'Posting only possible in periods 2026/07 and 2026/06 in company code 1000' (Message M7 053). What is the root cause and how do you resolve it?",
    "idealAnswer": "Root Cause: The MM posting period for the current calendar month is closed. SAP MM permits inventory postings only in the current open period and the immediately preceding period. Solution: 1) Verify current open period in T-Code MMRV for Company Code 1000. 2) Execute T-Code MMPV (Close Periods for Material Master Records) to roll the period forward to 2026/08. 3) If FI posting periods are also closed, coordinate with the finance team to open the posting period variant in T-Code OB52. 4) Re-post the MIGO goods receipt.",
    "keyPhrasesExpected": [
      "MMPV Period Roll Forward",
      "MMRV Check Open Period",
      "OB52 FI Posting Periods",
      "Message M7 053",
      "Current and previous period rule"
    ],
    "consultantThinkingTip": "Explain that MMPV is typically automated as a scheduled monthly background job (program RMMMINIT).",
    "followUpQuestions": [
      "Can an MM period be rolled backward after running MMPV?",
      "What is the 'Allow posting to previous period' flag in MMRV?"
    ],
    "difficultyScore": 5
  },
  {
    "id": "int-13",
    "module": "MM",
    "category": "Troubleshooting",
    "tier": "Troubleshooting",
    "question": "During MIGO Goods Issue (Movement Type 201), the transaction fails with error 'Account 400000 requires an assignment to a CO object' (Message KI 235). How do you investigate and fix this?",
    "idealAnswer": "Root Cause: G/L Account 400000 is defined as a Primary Cost Element (Category 1) in SAP Controlling (CO). Therefore, all postings to this account mandate a cost-controlling object (Cost Center, Internal Order, or WBS Element) to capture the expense. Solution: 1) Check if the user entered a Cost Center on the Account Assignment tab in MIGO. 2) If the transaction is automated and requires a default Cost Center, configure automatic account assignment in T-Code OKB9 for Company Code, Plant, and G/L Account 400000. 3) Re-execute the goods movement.",
    "keyPhrasesExpected": [
      "Primary Cost Element (Category 1)",
      "Mandatory CO Object (Cost Center / WBS)",
      "T-Code OKB9 Default Account Assignment",
      "Message KI 235"
    ],
    "consultantThinkingTip": "Highlight the integration touchpoint between MM Inventory Management and CO Controlling cost elements.",
    "followUpQuestions": [
      "What is the difference between OKB9 and KA02 default cost centers?",
      "How does this apply to Purchase Orders with Account Assignment 'K'?"
    ],
    "difficultyScore": 6
  },
  {
    "id": "int-14",
    "module": "MM",
    "category": "Troubleshooting",
    "tier": "Troubleshooting",
    "question": "A buyer releases a Purchase Order, but the output status in Output Parameter Determination (OPD) remains in 'Error' status. What diagnostic steps do you take?",
    "idealAnswer": "1) Open the PO in ME23N or Fiori 'Manage Purchase Orders' -> go to Output Items tab -> click the 'Log' icon next to the errored output item to view the technical error message. 2) Common causes: a) Missing email address in Business Partner communication data (BUT000 / ADR6); b) Invalid Form Template assignment in OPD (Adobe Form MM_PUR_PO not deployed); c) Adobe Document Services (ADS) connection failure between S/4HANA and NetWeaver Java / BTP. 3) Check transaction SOST / SCOT for outgoing email transmission logs. 4) Correct the master data or OPD rule, and re-trigger output.",
    "keyPhrasesExpected": [
      "OPD Output Item Log",
      "Business Partner communication email",
      "Adobe Document Services (ADS)",
      "Transaction SOST / SCOT email queue",
      "Form Template MM_PUR_PO"
    ],
    "consultantThinkingTip": "Contrasting S/4HANA OPD troubleshooting with legacy NAST / ME9F shows deep modern S/4HANA capability.",
    "followUpQuestions": [
      "How do you reprocess an errored output item in S/4HANA?",
      "What transaction is used to test ADS connection (FP_TEST_00)?"
    ],
    "difficultyScore": 7
  },
  {
    "id": "int-15",
    "module": "MM",
    "category": "Project Implementation",
    "tier": "Consultant",
    "question": "Explain the 6 phases of the SAP Activate Methodology and detail a functional consultant's primary deliverables during Explore, Realize, and Deploy.",
    "idealAnswer": "The 6 phases are Discover, Prepare, Explore, Realize, Deploy, and Run. In Explore: Consultant conducts Fit-to-Standard workshops using live SAP Best Practice scope items, validates standard workflows, identifies delta requirements (Gaps), and creates the Product Backlog and Business Requirement Documents (BRDs). In Realize: Consultant configures SPRO in iterative agile sprints, authors Functional Specifications (FSDs) for RICEFW objects, executes System Integration Testing (SIT), and runs Mock Data Migrations 1 & 2. In Deploy: Consultant executes the hour-by-hour Cutover Runbook, leads master data and open items migration via Migration Cockpit (LTMC), conducts end-user training, and achieves Go-Live.",
    "keyPhrasesExpected": [
      "6 Phases: Discover, Prepare, Explore, Realize, Deploy, Run",
      "Explore: Fit-to-Standard workshops & Backlog",
      "Realize: SPRO agile sprints, FSDs, SIT, UAT, Mock Cutover",
      "Deploy: Cutover Runbook, LTMC Migration, Go-Live",
      "Run: Hypercare & AMS handover"
    ],
    "consultantThinkingTip": "Contrast SAP Activate's agile Fit-to-Standard approach against classic ASAP's linear waterfall blueprinting.",
    "followUpQuestions": [
      "What is a Quality Gate (Q-Gate) in SAP Activate?",
      "What tool manages test scripts in SAP Activate (Cloud ALM)?"
    ],
    "difficultyScore": 9
  },
  {
    "id": "int-16",
    "module": "MM",
    "category": "Data Migration",
    "tier": "Consultant",
    "question": "What is the mandatory data migration sequence for SAP MM during Cutover and what is 'Triple Reconciliation' during initial stock upload (Movement 561)?",
    "idealAnswer": "Migration Sequence: 1) Business Partner (Suppliers in BUT000/LFA1/LFM1), 2) Material Master (MARA/MARC/MARD/MBEW), 3) Purchasing Info Records (EINA/EINE), 4) Source List (EORD), 5) Open Purchase Orders (EKKO/EKPO), 6) Initial Stock Upload (Movement 561 in MATDOC). Triple Reconciliation reconciles three layers: a) Physical Quantity (Legacy count sheet = SAP MB52/MMBE total units); b) Subledger Valuation (Total units * Standard price in MBEW = Material Document value in MATDOC); c) General Ledger (Debit to G/L Inventory Account BSX = Credit to Balance Sheet Cutover Equity account in Financial Trial Balance to the exact cent).",
    "keyPhrasesExpected": [
      "Prerequisite loading sequence (BP -> Material -> PIR -> Source List -> Open PO -> Stock)",
      "Movement Type 561",
      "Triple Reconciliation: Physical Count = Subledger MATDOC = General Ledger Trial Balance (BSX)"
    ],
    "consultantThinkingTip": "Explaining triple reconciliation demonstrates that you understand the financial and statutory audit gravity of a production Go-Live.",
    "followUpQuestions": [
      "What transaction is used to upload data in S/4HANA (LTMC / Migrate Your Data)?",
      "How do you handle open PO line items where partial goods receipt was posted in legacy?"
    ],
    "difficultyScore": 9
  },
  {
    "id": "int-17",
    "module": "MM",
    "category": "Cloud Transformation",
    "tier": "Consultant",
    "question": "Compare RISE with SAP and GROW with SAP. How do you advise an enterprise client on choosing between SAP S/4HANA Cloud Public Edition and Private Edition?",
    "idealAnswer": "GROW with SAP is a turnkey offering tailored for net-new midmarket organizations adopting SAP S/4HANA Cloud Public Edition. It is a multi-tenant SaaS offering with pre-configured Best Practices, continuous semi-annual automated upgrades, Greenfield deployment only, and a strict, non-negotiable Clean Core. RISE with SAP is a comprehensive Business Transformation as a Service (BTaaS) offering primarily focused on SAP S/4HANA Cloud Private Edition (single-tenant dedicated instance) and legacy ECC migrations. It supports 1-step Brownfield system conversions (SUM/DMO), full SPRO customizing depth, customer-managed annual upgrade cycles, and includes SAP Signavio process transformation and BTP cloud credits. Selection Framework: If the client has heavy legacy customizations, regulatory requirements for dedicated infrastructure, or needs Brownfield conversion -> Recommend RISE (Private Cloud). If the client is net-new, agile, and wants standard SaaS with lowest TCO -> Recommend GROW (Public Cloud).",
    "keyPhrasesExpected": [
      "GROW with SAP = Public Cloud Multi-tenant SaaS (Greenfield only, Clean Core)",
      "RISE with SAP = BTaaS / Private Cloud Single-tenant (Brownfield conversion supported, full SPRO)",
      "SAP Signavio and BTP inclusion",
      "Upgrade cycle governance (Semi-annual automated vs Annual customer-controlled)",
      "Clean Core Strategy"
    ],
    "consultantThinkingTip": "Highlight that large enterprises can adopt a 2-Tier ERP model: Corporate core on RISE (Private Cloud) and agile regional subsidiaries on GROW (Public Cloud).",
    "followUpQuestions": [
      "What is In-App Extensibility vs Side-by-Side Extensibility on BTP?",
      "How does SAP Signavio assist in the Discover and Explore phases?"
    ],
    "difficultyScore": 10
  },
  {
    "id": "int-18",
    "module": "INTEGRATION",
    "category": "MM + EWM Integration",
    "tier": "Consultant",
    "question": "Explain the role of the 2-Storage Location strategy (ROD vs AFS) and Process-Oriented Storage Control (POSC) in MM-EWM Integration.",
    "idealAnswer": "In MM-EWM integration, the 2-Storage Location strategy segregates received goods from available stock. When an Inbound Delivery (VL31N / /SCWM/PRDI) arrives, Goods Receipt (101) is posted against Storage Location 'ROD' (Received on Dock). This stock is physically inside the building but not yet available for customer sales or production consumption. EWM POSC (Process-Oriented Storage Control) then executes multi-step physical routing: Step 1 Unload -> Step 2 Deconsolidate -> Step 3 Quality Inspection -> Step 4 Final Bin Putaway. When the final putaway Warehouse Task is confirmed in EWM, the system automatically posts an internal Posting Change (Transfer Posting 311) in MM, moving the stock from ROD to 'AFS' (Available for Sale).",
    "keyPhrasesExpected": [
      "2-Storage Location Strategy: ROD (Received on Dock) vs AFS (Available for Sale)",
      "Inbound Delivery (VL31N / /SCWM/PRDI)",
      "POSC multi-step routing (UNLD, DECO, QIS, PUTW)",
      "Automated 311 Posting Change upon final putaway confirmation",
      "Handling Unit Management (HUM)"
    ],
    "consultantThinkingTip": "Describe the real-time queue synchronization via qRFC between S/4HANA Logistics Execution and Embedded/Decentralized EWM.",
    "followUpQuestions": [
      "What transaction is used to monitor EWM warehouse stock and queues (/SCWM/MON)?",
      "What is Layout-Oriented Storage Control (LOSC)?"
    ],
    "difficultyScore": 9
  }
];
